### PR TITLE
[Feat] BadPacketC: Impossible slot change packet check

### PR DESCRIPTION
**Pull request by athulsib**
In minecraft its impossible to send the same slot packet.

I've had this check in my anticheat as a general badpackets check for a while, I've noticed it flags many poorly built modules like Autototem, CrystalAura, AnchorAura, CartAura (in a private client).

Even though this is a very basic check, alot of clients somehow mess this up. Pretty Sure meteor or some other popular client flags this lol.

ps; not sure if I implemented it correctly, im not familiar with this base so do make sure it works.

### CODE REVIEW

**Comment by athulsib** [comment]
tip: I would recommend instantly kicking on a single flag (ban after multiple kicks). On my server I used this as one of the crystalaura checks bc it flags more often. Since you dont pop totems as much as crystals, waiting for 3 flags or smthn before ban takes alot of time.

**Comment by Bram1903** [comment]
Hey,

Thanks for the PR!

You implemented this new check almost perfectly! Due to the way my base works, you missed clearing/removing values when someone leaves, which is triggered by the resetData event. That’s mostly due to how my base is structured, so no worries there.

The base was written by me but has evolved organically since the start of this project rather than being properly designed. I’ve been thinking about redoing it in the future, but for now, it works well enough 😅.

Regarding the multiple kick-to-ban message: is there any scenario where a false positive might occur? If not, we could just instantly ban, similar to the other badpacket checks.

Once again, thanks for the PR! I’ll do some quick testing once I get home (currently on the train back from uni), and if everything looks good, I’ll merge it into the main branch.

Kind regards,
Bram

**Review by Bram1903 — APPROVED** [review]

**Comment by athulsib** [comment]
Hey,

This is actually a very well-known check among anti-cheats. it really is impossible to send the same slot packets. The reason for keeping a buffer/threshold for the ban is simply for the sake of having a buffer and nothing else. If, by some miracle—by the will of God and the universe itself—this falses, then the buffer acts as a safeguard.

**Comment by Bram1903** [comment]
Thanks a lot for your PR!

**Pull request merged**
